package org.hartz.hartz_backend.exception;

public class UsernameTakenException extends RuntimeException {
}
