package org.hartz.hartz_backend.exception.userExceptions;

public class UsernameTakenException extends RuntimeException {
}
