package org.hartz.hartz_backend.common.exception;

public class UsernameTakenException extends RuntimeException {
}
